services:
  - type: web
    name: backend-django
    env: python
    buildCommand: poetry install
    startCommand: poetry run gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings


