services:
  - type: web
    name: backend-django
    env: python
    buildCommand: pip install -r backend/requirements.txt   # Ajusta la ruta
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings


